### PR TITLE
AIC and BIC methods for mjoint objects

### PR DESCRIPTION
**Pull request by ellessenne**
Hi,
I noticed a while ago that calling the BIC function on an object of class `mjoint` there were discrepancies with the values reported by `summary.mjoint`. I then checked the actual calculations and implemented the methods `AIC.mjoint` and `BIC.mjoint` - now the results should be consistent!

### CODE REVIEW

**Comment by graemeleehickey** [comment]
Thanks Alessandro. I think Pete Philpson will need to pull these to add
them.

Graeme

**Comment by graemeleehickey** [comment]
@petephilipson -- Can you merge please?

**Comment by ellessenne** [comment]
Hi @graemeleehickey @petephilipson, is there any chance to get this merged?

**Comment by graemeleehickey** [comment]
Hi Pete,

Please can you respond to Alessandro? Perhaps would be good to provide him
with author access to the repo?

Thanks,

Graeme

**Comment by petephilipson** [comment]
Hi Graeme,

This is now done! Sorry for the wait, it has been marking season and I was way for a few days at the SAM conference in Manchester.

Best wishes, Pete.

**Comment by graemeleehickey** [comment]
Pete confirmed this has been added.

**Pull request closed without merging**
